# Generated by Django 3.2.5 on 2021-11-11 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoAnotateExampleApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cities',
            new_name='City',
        ),
    ]
