# Generated by Django 3.2.5 on 2021-11-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoAnotateExampleApp', '0002_rename_cities_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='population',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
