# Generated by Django 3.2.5 on 2021-11-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelAdminRevisionApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='email',
            field=models.EmailField(default='', max_length=200, null=True),
        ),
    ]
