# Generated by Django 3.2.5 on 2021-11-01 10:43

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('ManagerModelApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ManagerModelApp.post',),
            managers=[
                ('custom', django.db.models.manager.Manager()),
            ],
        ),
    ]
